PACKAGE_NAME="alx-wol"
PACKAGE_VERSION="3.1"

BUILT_MODULE_NAME[0]="alx"
BUILT_MODULE_LOCATION[0]="alx/"
DEST_MODULE_NAME[0]="alx"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/atheros/alx"

AUTOINSTALL="yes"
PRE_BUILD="scripts/fetchsources.sh $install_tree"

orig_loc="${install_tree}/${kernelver}${DEST_MODULE_LOCATION[0]}"
new_loc="${install_tree}/${kernelver}$(override_dest_module_location "${DEST_MODULE_LOCATION[0]}")"
POST_INSTALL="scripts/handleinitrd.sh \"${kernelver}\" install \"$orig_loc\" \"$new_loc\""
POST_REMOVE="scripts/handleinitrd.sh \"${kernelver}\" remove \"$orig_loc\" \"$new_loc\""

if [ "${module}" != "" ]; then
	build="${dkms_tree}/${module}/${module_version}/build"
	select_gcc="${source_tree}/${module}-${module_version}/scripts/select_gcc.sh"
	gcc_used=$(grep CONFIG_CC_VERSION_TEXT $install_tree/$kernelver/build/include/config/auto.conf | sed -n 's|^.*\s\([0-9]\+\.[0-9]\+\.[0-9]\+\)\s*.*$|\1|g;p')
	temp="${dkms_tree}/${module}/${module_version}/${kernelver}"
	gcc_exe="$("${select_gcc}" "${arch}" "${build}" "${gcc_used}")"
	MAKE[0]="make -C \"$kernel_source_dir\" M=\"$dkms_tree/$module/$module_version/build\" HOSTCC=\"${gcc_exe}\" CC=\"${gcc_exe}\""
fi
